hough_thresh = 10         # 最低投票数（これ以上で直線と判断）
min_len = 18              # 検出する線分の最小長さ（ピクセル）
max_gap = 4               # 線分の最大切れ目（ピクセル）
tol_theta_deg = 5.0       # 角度差の許容範囲（度）
tol_rho_px = 10.0         # ρの許容誤差（ピクセル）
dot_radius = 7            # 端点マークの円半径（ピクセル）
angle_thr_deg = 25.0      # 傾きがこの角度以下の線のみ対象
edge_pct = 0.20           # 上下の黒影領域の割合
side_pct = 0.12           # 左右の端領域の割合
